// src/renderer/components/FMCard.vue
<script setup lang="ts">
import { average } from 'color.js'
import { colord } from 'colord'

const background = ref<string>('')
const coverUrl = ref<string>(
  // 'https://p2.music.126.net/-_zf-SC10UEHxCbJB5h0PA==/109951165985694735.jpg?param=512y512'
  // 'https://p1.music.126.net/2jls9nqjYYlQEybpHPaccw==/109951164706184612.jpg?param=512y512'
  'https://p1.music.126.net/lEzPSOjusKaRXKXT3987lQ==/109951166035876388.jpg?param=512y512'
  // 'https://p1.music.126.net/6CB6Jsmb7k7qiJqfMY5Row==/109951164260234943.jpg?param=512y512'
  // 'https://p2.music.126.net/AhYP9TET8l-VSGOpWAKZXw==/109951165134386387.jpg?param=512y512'
  // 'https://p2.music.126.net/vCTNT88k1rnflXtDdmWT9g==/109951165359041202.jpg?param=512y512'
  // 'https://p2.music.126.net/QxJA2mr4hhb9DZyucIOIQw==/109951165422200291.jpg?param=512y512'
)

average(coverUrl.value, { amount: 1, format: 'hex', sample: 1 }).then(color => {
  const to = colord(color as string)
    .darken(0.15)
    .rotate(-5)
    .toHex()
  background.value = `linear-gradient(to bottom right, ${color}, ${to})`
})
</script>

<template>
  <div
    class="relative flex h-[198px] overflow-hidden rounded-2xl p-4"
    :style="{ background }"
  >
    <!-- cover -->
    <img class="rounded-xl shadow-2xl" :src="coverUrl" />

    <!-- track info  -->
    <div class="ml-5 flex w-full flex-col justify-between text-white">
      <div>
        <div class="text-xl font-semibold">How Can I Make It OK?</div>
        <div class="opacity-75">Wolf Alice</div>
      </div>
      <div class="flex items-center justify-between">
        <!-- buttons -->
        <div>
          <button
            v-for="action in ['dislike', 'play', 'next']"
            class="btn-pressed-animation btn-hover-animation mr-1 cursor-default rounded-lg p-2 transition duration-200 after:bg-white/10"
            ><SvgIcon :name="action" class="h-5 w-5"
          /></button>
        </div>

        <!-- fm symbol  -->
        <div class="right-4 bottom-5 flex text-white opacity-20">
          <SvgIcon name="fm" class="mr-2 h-5 w-5" />
          <span class="font-semibold">私人FM</span>
        </div>
      </div>
    </div>
  </div>
</template>

// packages/renderer/src/components/FMCard.tsx
import { average } from 'color.js'
import { colord } from 'colord'
import SvgIcon from '@/components/SvgIcon'

enum ACTION {
  DISLIKE = 'dislike',
  PLAY = 'play',
  NEXT = 'next',
}

const FMCard = () => {
  const coverUrl =
    'https://p1.music.126.net/lEzPSOjusKaRXKXT3987lQ==/109951166035876388.jpg?param=512y512'
  const [background, setBackground] = useState('')

  useEffect(() => {
    average(coverUrl, { amount: 1, format: 'hex', sample: 1 }).then(color => {
      const to = colord(color as string)
        .darken(0.15)
        .rotate(-5)
        .toHex()
      setBackground(`linear-gradient(to bottom right, ${color}, ${to})`)
    })
  }, [coverUrl])

  return (
    <div
      className='relative flex h-[198px] overflow-hidden rounded-2xl p-4'
      style={{ background }}
    >
      <img className='rounded-lg shadow-2xl' src={coverUrl} />

      <div className='ml-5 flex w-full flex-col justify-between text-white'>
        {/* Track info */}
        <div>
          <div className='text-xl font-semibold'>How Can I Make It OK?</div>
          <div className='opacity-75'>Wolf Alice</div>
        </div>

        <div className='-mb-1 flex items-center justify-between'>
          {/* Actions */}

          <div>
            {Object.values(ACTION).map(action => (
              <button
                key={action}
                className='btn-pressed-animation btn-hover-animation mr-1 cursor-default rounded-lg p-1.5 transition duration-200 after:bg-white/10'
              >
                <SvgIcon name={action} className='h-6 w-6' />
              </button>
            ))}
          </div>

          {/* FM logo */}
          <div className='right-4 bottom-5 flex text-white opacity-20'>
            <SvgIcon name='fm' className='mr-1 h-6 w-6' />
            <span className='font-semibold'>私人FM</span>
          </div>
        </div>
      </div>
    </div>
  )
}

export default FMCard
