// src/renderer/views/Album.vue
<script setup lang="ts">
import { resizeImage, formatDuration, formatDate } from '@renderer/utils/common'
import useAlbum from '@renderer/hooks/useAlbum'
import dayjs from 'dayjs'
import useArtistAlbums from '@renderer/hooks/useArtistAlbums'
import usePlayer, { PlayerState } from '@renderer/hooks/usePlayer'

const router = useRouter()
const route = useRoute()
const { t, locale } = useI18n()

// Validate album id
const albumID = computed(() => route.params.id as string)
if (!albumID.value || isNaN(Number(albumID.value))) {
  router.replace('/404')
}

// Fetch album data
const { data: albumRaw, isLoading } = useAlbum(
  reactive({
    id: albumID,
  })
)
const album = computed(() => {
  return albumRaw?.value?.album
})
const tracks = computed(() => {
  return albumRaw?.value?.songs
})
const coverUrl = computed(() => {
  return resizeImage(album?.value?.picUrl || '', 'lg')
})
const albumDuration = computed(() => {
  const duration = tracks.value?.reduce((acc, cur) => acc + cur.dt, 0) || 0
  return formatDuration(duration, locale.value, 'hh[hr] mm[min]')
})

// Fetch artist's albums
const { data: otherAlbums, isLoading: isLoadingMoreAlbums } = useArtistAlbums(
  reactive({
    id: computed(() => album.value?.artist.id || 0),
  })
)
const filteredOtherAlbums = computed((): Album[] => {
  const allReleases = otherAlbums.value?.hotAlbums || []
  const albums = allReleases.filter(
    album => ['专辑', 'EP/Single', 'EP'].includes(album.type) && album.size > 1
  )
  const singles = allReleases.filter(album => album.type === 'Single')

  // 去除名字相同的专辑和当前页面显示的专辑
  const deDuplicatedAlbums: Album[] = []
  albums.forEach(album => {
    if (
      deDuplicatedAlbums.findIndex(a => a.name === album.name) === -1 &&
      String(album.id) !== albumID.value
    ) {
      deDuplicatedAlbums.push(album)
    }
  })

  return [...deDuplicatedAlbums, ...singles].slice(0, 5)
})

// Handle play album
const player = usePlayer()
const play = () => {
  player?.replacePlaylist(tracks.value?.map(s => s.id) || [], {
    type: 'album',
    id: albumID.value,
  })
}
</script>

<template>
  <div class="mt-10">
    <!-- Header background -->
    <div class="absolute top-0 left-0 z-0 h-[24rem] w-full overflow-hidden">
      <img :src="coverUrl" class="absolute top-0 w-full blur-[100px]" />
      <img :src="coverUrl" class="absolute top-0 w-full blur-[100px]" />
      <div
        class="absolute top-0 h-full w-full bg-gradient-to-b from-[#ffffffd6] to-white/100"
      ></div>
    </div>

    <div class="grid grid-cols-[17rem_auto] items-center gap-10">
      <!-- Cover -->
      <div class="relative z-0 aspect-square self-start">
        <div
          v-if="!isLoading"
          class="absolute top-3.5 z-[-1] h-full w-full scale-x-[.92] scale-y-[.96] rounded-2xl bg-cover opacity-60 blur-lg filter"
          :style="{
            backgroundImage: `url(&quot;${coverUrl}&quot;)`,
          }"
        ></div>

        <img
          v-if="!isLoading"
          :src="coverUrl"
          class="rounded-2xl border border-black border-opacity-5"
        />
        <Skeleton v-else class="h-full w-full rounded-2xl" />
      </div>

      <!-- Album info -->
      <div class="z-10">
        <!-- Name -->
        <div v-if="!isLoading" class="text-6xl font-bold">{{
          album?.name
        }}</div>
        <Skeleton v-else class="w-3/4 text-7xl">PLACEHOLDER</Skeleton>

        <!-- Artist -->
        <div v-if="!isLoading" class="mt-5 text-lg font-medium text-gray-800">
          Album by
          <span class="font-semibold decoration-2 hover:underline">{{
            album?.artist.name
          }}</span>
        </div>
        <Skeleton v-else class="mt-5 w-64 text-lg">PLACEHOLDER</Skeleton>

        <!-- Last update time & track count -->
        <div v-if="!isLoading" class="text-sm font-thin text-gray-500">
          {{ dayjs(album?.publishTime || 0).year() }} · {{ album?.size }} Songs,
          {{ albumDuration }}
        </div>
        <Skeleton v-else class="w-72 translate-y-px text-sm"
          >PLACEHOLDER</Skeleton
        >

        <!-- Description -->
        <div
          v-if="!isLoading"
          class="line-clamp-3 mt-5 min-h-[3.75rem] max-w-xl text-sm text-gray-500"
        >
          {{ album?.description }}
        </div>
        <Skeleton v-else class="mt-5 min-h-[3.75rem] w-1/2 text-sm"
          >PLACEHOLDER</Skeleton
        >

        <!-- Buttons -->
        <div class="mt-5 flex gap-4">
          <Button @click="play" :isSkelton="isLoading">
            <SvgIcon name="play" class="mr-2 h-4 w-4" />
            PLAY
          </Button>

          <Button :isSkelton="isLoading" shape="square" color="gray">
            <SvgIcon name="heart" class="h-4 w-4" />
          </Button>
          <Button
            :isSkelton="isLoading"
            shape="square"
            color="gray"
            iconColor="gray"
          >
            <SvgIcon name="more" class="h-4 w-4" />
          </Button>
        </div>
      </div>
    </div>

    <!-- Tracks table header -->
    <div
      class="mx-4 mt-10 mb-2 grid grid-cols-12 border-b border-gray-100 py-2.5 text-sm text-gray-400"
    >
      <div class="col-span-6 grid grid-cols-[2rem_auto]">
        <div>#</div>
        <div>TITLE</div>
      </div>
      <div class="col-span-4">ARTIST</div>
      <div class="col-span-2 justify-self-end">TIME</div>
    </div>

    <!-- Tracks -->
    <TrackList :tracks="tracks || []" layout="album" :isLoading="isLoading" />

    <!-- Release date and company -->
    <div class="mt-5 text-xs text-gray-400">
      <div> Released {{ formatDate(album?.publishTime || 0, locale) }} </div>
      <div v-if="album?.company" class="mt-[2px]">© {{ album?.company }} </div>
    </div>

    <!-- More by artist -->
    <div class="my-5 h-px w-full bg-gray-100"></div>
    <div class="pl-px text-[1.375rem] font-semibold text-gray-800"
      >More by
      <router-link
        :to="{ name: 'artist', params: { id: album?.artist.id } }"
        class="hover:underline"
        >{{ album?.artist.name }}</router-link
      ></div
    >
    <div class="mt-3">
      <CoverRow
        :albums="filteredOtherAlbums"
        :isSkeleton="isLoadingMoreAlbums"
        subtitle="type+releaseYear"
      />
    </div>
  </div>
</template>

// packages/web/pages/Album.tsx
import dayjs from 'dayjs'
import { NavLink, useParams } from 'react-router-dom'
import Button, { Color as ButtonColor } from '@/web/components/Button'
import CoverRow, { Subtitle } from '@/web/components/CoverRow'
import Skeleton from '@/web/components/Skeleton'
import SvgIcon from '@/web/components/SvgIcon'
import TracksAlbum from '@/web/components/TracksAlbum'
import useAlbum from '@/web/hooks/useAlbum'
import useArtistAlbums from '@/web/hooks/useArtistAlbums'
import { player } from '@/web/store'
import {
  Mode as PlayerMode,
  State as PlayerState,
  TrackListSourceType,
} from '@/web/utils/player'
import {
  formatDate,
  formatDuration,
  resizeImage,
  scrollToTop,
} from '@/web/utils/common'
import useTracks from '@/web/hooks/useTracks'
import useUserAlbums, {
  useMutationLikeAAlbum,
} from '@/web/hooks/useUserAlbums'
import { useMemo, useState } from 'react'
import toast from 'react-hot-toast'
import { useSnapshot } from 'valtio'

const PlayButton = ({
  album,
  handlePlay,
  isLoading,
}: {
  album: Album | undefined
  handlePlay: () => void
  isLoading: boolean
}) => {
  const playerSnapshot = useSnapshot(player)
  const isThisAlbumPlaying = useMemo(
    () =>
      playerSnapshot.mode === PlayerMode.TrackList &&
      playerSnapshot.trackListSource?.type === TrackListSourceType.Album &&
      playerSnapshot.trackListSource?.id === album?.id,
    [
      playerSnapshot.mode,
      playerSnapshot.trackListSource?.type,
      playerSnapshot.trackListSource?.id,
      album?.id,
    ]
  )

  const isPlaying =
    isThisAlbumPlaying &&
    [PlayerState.Playing, PlayerState.Loading].includes(playerSnapshot.state)

  const wrappedHandlePlay = () => {
    if (isThisAlbumPlaying) {
      player.playOrPause()
    } else {
      handlePlay()
    }
  }

  return (
    <Button onClick={wrappedHandlePlay} isSkelton={isLoading}>
      <SvgIcon
        name={isPlaying ? 'pause' : 'play'}
        className='mr-1 -ml-1 h-6 w-6'
      />
      {isPlaying ? '暂停' : '播放'}
    </Button>
  )
}

const Header = ({
  album,
  isLoading,
  handlePlay,
}: {
  album: Album | undefined
  isLoading: boolean
  handlePlay: () => void
}) => {
  const coverUrl = resizeImage(album?.picUrl || '', 'lg')

  const albumDuration = useMemo(() => {
    const duration = album?.songs?.reduce((acc, cur) => acc + cur.dt, 0) || 0
    return formatDuration(duration, 'zh-CN', 'hh[hr] mm[min]')
  }, [album?.songs])

  const [isCoverError, setCoverError] = useState(
    coverUrl.includes('3132508627578625')
  )

  const { data: userAlbums } = useUserAlbums()
  const isThisAlbumLiked = useMemo(() => {
    if (!album) return false
    return !!userAlbums?.data?.find(a => a.id === album.id)
  }, [album, userAlbums?.data])
  const mutationLikeAAlbum = useMutationLikeAAlbum()

  return (
    <>
      {/* Header background */}
      <div className='absolute top-0 left-0 z-0 h-[24rem] w-full overflow-hidden'>
        {coverUrl && !isCoverError && (
          <>
            <img
              src={coverUrl}
              className='absolute -top-full w-full blur-[100px]'
            />
            <img
              src={coverUrl}
              className='absolute -top-full w-full blur-[100px]'
            />
          </>
        )}
        <div className='absolute top-0 h-full w-full bg-gradient-to-b from-white/[.85] to-white dark:from-black/50 dark:to-[#1d1d1d]'></div>
      </div>

      <div className='grid grid-cols-[17rem_auto] items-center gap-9'>
        {/*  Cover */}
        <div className='relative z-0 aspect-square self-start'>
          {/* Neon shadow */}
          {!isLoading && coverUrl && !isCoverError && (
            <div
              className='absolute top-3.5 z-[-1] h-full w-full scale-x-[.92] scale-y-[.96] rounded-2xl bg-cover opacity-40 blur-lg filter'
              style={{
                backgroundImage: `url("${coverUrl}")`,
              }}
            ></div>
          )}

          {!isLoading && isCoverError ? (
            // Fallback cover
            <div className='flex h-full w-full items-center justify-center rounded-2xl border border-black border-opacity-5 bg-gray-100 text-gray-300'>
              <SvgIcon name='music-note' className='h-1/2 w-1/2' />
            </div>
          ) : (
            coverUrl && (
              <img
                src={coverUrl}
                className='w-full rounded-2xl border border-b-0 border-black border-opacity-5 dark:border-white dark:border-opacity-5'
                onError={() => setCoverError(true)}
              />
            )
          )}
          {isLoading && <Skeleton className='h-full w-full rounded-2xl' />}
        </div>

        {/* Info */}
        <div className='z-10 flex h-full flex-col justify-between'>
          {/*  Name */}
          {isLoading ? (
            <Skeleton className='w-3/4 text-6xl'>PLACEHOLDER</Skeleton>
          ) : (
            <div className='text-6xl font-bold dark:text-white'>
              {album?.name}
            </div>
          )}

          {/*  Artist */}
          {isLoading ? (
            <Skeleton className='mt-5 w-64 text-lg'>PLACEHOLDER</Skeleton>
          ) : (
            <div className='mt-5 text-lg font-medium text-gray-800 dark:text-gray-300'>
              Album ·{' '}
              <NavLink
                to={`/artist/${album?.artist.id}`}
                className='cursor-default font-semibold hover:underline'
              >
                {album?.artist.name}
              </NavLink>
            </div>
          )}

          {/* Release date & track count & album duration */}
          {isLoading ? (
            <Skeleton className='w-72 translate-y-px text-sm'>
              PLACEHOLDER
            </Skeleton>
          ) : (
            <div className='flex items-center text-sm text-gray-500 dark:text-gray-400'>
              {album?.mark === 1056768 && (
                <SvgIcon
                  name='explicit'
                  className='mt-px mr-1 h-4 w-4 text-gray-400 dark:text-gray-500'
                />
              )}
              {dayjs(album?.publishTime || 0).year()} · {album?.size} 首歌 ·{' '}
              {albumDuration}
            </div>
          )}

          {/* Description */}
          {isLoading ? (
            <Skeleton className='mt-5 min-h-[2.5rem] w-1/2 text-sm'>
              PLACEHOLDER
            </Skeleton>
          ) : (
            <div className='line-clamp-2 mt-5 min-h-[2.5rem] text-sm text-gray-500 dark:text-gray-400'>
              {album?.description}
            </div>
          )}

          {/*  Buttons */}
          <div className='mt-5 flex gap-4'>
            <PlayButton {...{ album, handlePlay, isLoading }} />

            <Button
              color={ButtonColor.Gray}
              iconColor={
                isThisAlbumLiked ? ButtonColor.Primary : ButtonColor.Gray
              }
              isSkelton={isLoading}
              onClick={() => album?.id && mutationLikeAAlbum.mutate(album)}
            >
              <SvgIcon
                name={isThisAlbumLiked ? 'heart' : 'heart-outline'}
                className='h-6 w-6'
              />
            </Button>

            <Button
              color={ButtonColor.Gray}
              iconColor={ButtonColor.Gray}
              isSkelton={isLoading}
              onClick={() => toast('施工中...')}
            >
              <SvgIcon name='more' className='h-6 w-6' />
            </Button>
          </div>
        </div>
      </div>
    </>
  )
}

const MoreAlbum = ({ album }: { album: Album | undefined }) => {
  // Fetch artist's albums
  const { data: albums, isLoading } = useArtistAlbums({
    id: album?.artist.id ?? 0,
    limit: 1000,
  })

  const filteredAlbums = useMemo((): Album[] => {
    if (!albums) return []
    const allReleases = albums?.hotAlbums || []
    const filteredAlbums = allReleases.filter(
      album =>
        ['专辑', 'EP/Single', 'EP'].includes(album.type) && album.size > 1
    )
    const singles = allReleases.filter(album => album.type === 'Single')

    const qualifiedAlbums = [...filteredAlbums, ...singles]

    const formatName = (name: string) =>
      name.toLowerCase().replace(/(\s|deluxe|edition|\(|\))/g, '')

    const uniqueAlbums: Album[] = []
    qualifiedAlbums.forEach(a => {
      // 去除当前页面的专辑
      if (formatName(a.name) === formatName(album?.name ?? '')) return

      // 去除重复的专辑(包含 deluxe edition 的专辑会视为重复)
      if (
        uniqueAlbums.findIndex(aa => {
          return formatName(a.name) === formatName(aa.name)
        }) !== -1
      ) {
        return
      }

      // 去除 remix 专辑
      if (
        a.name.toLowerCase().includes('remix)') ||
        a.name.toLowerCase().includes('remixes)')
      ) {
        return
      }

      uniqueAlbums.push(a)
    })

    return uniqueAlbums.slice(0, 5)
  }, [album?.name, albums])

  return (
    <div>
      <div className='my-5 h-px w-full bg-gray-100 dark:bg-gray-800'></div>
      {!isLoading && albums?.hotAlbums?.length && (
        <div className='pl-px text-[1.375rem] font-semibold text-gray-800 dark:text-gray-100'>
          More by{' '}
          <NavLink
            to={`/artist/${album?.artist?.id}`}
            className='cursor-default hover:underline'
          >
            {album?.artist.name}
          </NavLink>
        </div>
      )}
      <div className='mt-3'>
        <CoverRow
          albums={
            filteredAlbums.length ? filteredAlbums : albums?.hotAlbums || []
          }
          subtitle={Subtitle.TypeReleaseYear}
          isSkeleton={isLoading}
          rows={1}
          navigateCallback={scrollToTop}
        />
      </div>
    </div>
  )
}

const Album = () => {
  const params = useParams()
  const { data: album, isLoading } = useAlbum({
    id: Number(params.id) || 0,
  })

  const { data: tracks } = useTracks({
    ids: album?.songs?.map(track => track.id) ?? [],
  })

  const handlePlay = async (trackID: number | null = null) => {
    if (!album?.album.id) {
      toast('无法播放专辑，该专辑不存在')
      return
    }
    await player.playAlbum(album.album.id, trackID)
  }

  return (
    <div className='mt-10'>
      <Header
        album={album?.album}
        isLoading={isLoading}
        handlePlay={handlePlay}
      />
      <TracksAlbum
        tracks={tracks?.songs ?? album?.album.songs ?? []}
        onTrackDoubleClick={handlePlay}
        isSkeleton={isLoading}
      />
      {album?.album && (
        <div className='mt-5 text-xs text-gray-400'>
          <div> Released {formatDate(album.album.publishTime || 0, 'en')} </div>
          {album.album.company && (
            <div className='mt-[2px]'>© {album.album.company} </div>
          )}
        </div>
      )}
      {!isLoading && <MoreAlbum album={album?.album} />}
    </div>
  )
}

export default Album
