// packages/web/pages/Home.tsx
import {
  fetchRecommendedPlaylists,
  fetchDailyRecommendPlaylists,
} from '@/web/api/playlist'
import CoverRow from '@/web/components/CoverRow'
import DailyTracksCard from '@/web/components/DailyTracksCard'
import FMCard from '@/web/components/FMCard'
import { PlaylistApiNames } from '@/shared/api/Playlists'
import { APIs } from '@/shared/CacheAPIs'
import { IpcChannels } from '@/shared/IpcChannels'
import { useQuery } from 'react-query'

export default function Home() {
  const {
    data: dailyRecommendPlaylists,
    isLoading: isLoadingDailyRecommendPlaylists,
  } = useQuery(
    PlaylistApiNames.FetchDailyRecommendPlaylists,
    fetchDailyRecommendPlaylists,
    {
      retry: false,
      placeholderData: () =>
        window.ipcRenderer?.sendSync(IpcChannels.GetApiCacheSync, {
          api: APIs.RecommendResource,
        }),
    }
  )

  const {
    data: recommendedPlaylists,
    isLoading: isLoadingRecommendedPlaylists,
  } = useQuery(
    PlaylistApiNames.FetchRecommendedPlaylists,
    () => {
      return fetchRecommendedPlaylists({})
    },
    {
      placeholderData: () =>
        window.ipcRenderer?.sendSync(IpcChannels.GetApiCacheSync, {
          api: APIs.Personalized,
        }),
    }
  )

  const playlists = [
    ...(dailyRecommendPlaylists?.recommend?.slice(1).slice(0, 8) ?? []),
    ...(recommendedPlaylists?.result ?? []),
  ].slice(0, 10)

  return (
    <div>
      <CoverRow
        title='推荐歌单'
        playlists={playlists}
        isSkeleton={
          isLoadingRecommendedPlaylists || isLoadingDailyRecommendPlaylists
        }
      />

      <div className='mt-10 mb-4 text-[28px] font-bold text-black dark:text-white'>
        For You
      </div>
      <div className='grid grid-cols-2 gap-6'>
        <DailyTracksCard />
        <FMCard />
      </div>
    </div>
  )
}

// src/renderer/views/Home.vue
<script setup lang="ts">
import { PlaylistApiNames } from '@renderer/api/playlist'
import { fetchRecommendedPlaylists } from '@renderer/api/playlist'

const router = useRouter()

const { data: recommendedPlaylists, isLoading: isLoadingRecommendedPlaylists } =
  useQuery(PlaylistApiNames.FETCH_RECOMMENDED_PLAYLISTS, () => {
    return fetchRecommendedPlaylists({})
  })
</script>

<template>
  <div>
    <CoverRow
      title="Good Morning"
      :playlists="recommendedPlaylists?.result.slice(0, 10) ?? []"
      :isSkeleton="isLoadingRecommendedPlaylists"
    />
    <div class="mt-10 mb-4 text-[28px] font-bold text-black dark:text-white"
      >For You</div
    >
    <div class="grid grid-cols-2 gap-6">
      <DailyTracksCard />
      <FMCard />
    </div>
  </div>
</template>
