// packages/web/pages/Login.tsx
import md5 from 'md5'
import QRCode from 'qrcode'
import {
  checkLoginQrCodeStatus,
  fetchLoginQrCodeKey,
  loginWithEmail,
  loginWithPhone,
} from '@/web/api/auth'
import SvgIcon from '@/web/components/SvgIcon'
import { state } from '@/web/store'
import { setCookies } from '@/web/utils/cookie'
import { useInterval } from 'react-use'
import cx from 'classnames'
import { useState, useMemo, useEffect } from 'react'
import toast from 'react-hot-toast'
import { useMutation, useQuery } from 'react-query'
import { useNavigate } from 'react-router-dom'
import { useSnapshot } from 'valtio'

enum Method {
  QrCode = 'qrcode',
  Email = 'email',
  Phone = 'phone',
}

const domParser = new DOMParser()

// Shared components and methods
const EmailInput = ({
  email,
  setEmail,
}: {
  email: string
  setEmail: (email: string) => void
}) => {
  return (
    <div className='w-full'>
      <div className='mb-1 text-sm font-medium text-gray-700 dark:text-gray-300'>
        邮箱
      </div>
      <input
        value={email}
        onChange={e => setEmail(e.target.value)}
        className='w-full rounded-md border border-gray-300 px-2 py-2 dark:border-gray-600 dark:bg-gray-700 dark:text-white'
        type='email'
      />
    </div>
  )
}

const PhoneInput = ({
  countryCode,
  setCountryCode,
  phone,
  setPhone,
}: {
  countryCode: string
  setCountryCode: (code: string) => void
  phone: string
  setPhone: (phone: string) => void
}) => {
  return (
    <div className='w-full'>
      <div className='mb-1 text-sm font-medium text-gray-700 dark:text-gray-300'>
        手机
      </div>
      <div className='flex w-full'>
        <input
          className={cx(
            'rounded-md rounded-r-none border border-r-0 border-gray-300 px-3 py-2 dark:border-gray-600 dark:bg-gray-700 dark:text-white',
            countryCode.length <= 3 && 'w-14',
            countryCode.length == 4 && 'w-16',
            countryCode.length >= 5 && 'w-20'
          )}
          type='text'
          placeholder='+86'
          value={countryCode}
          onChange={e => setCountryCode(e.target.value)}
        />
        <input
          className='flex-grow rounded-md rounded-l-none border border-gray-300 px-3 py-2 dark:border-gray-600 dark:bg-gray-700 dark:text-white'
          type='text'
          value={phone}
          onChange={e => setPhone(e.target.value)}
        />
      </div>
    </div>
  )
}

const PasswordInput = ({
  password,
  setPassword,
}: {
  password: string
  setPassword: (password: string) => void
}) => {
  const [showPassword, setShowPassword] = useState(false)
  return (
    <div className='mt-3 flex w-full flex-col'>
      <div className='mb-1 text-sm font-medium text-gray-700  dark:text-gray-300'>
        密码
      </div>
      <div className='flex w-full'>
        <input
          value={password}
          onChange={e => setPassword(e.target.value)}
          className='w-full rounded-md rounded-r-none border border-r-0 border-gray-300 px-2 py-2 dark:border-gray-600 dark:bg-gray-700 dark:text-white'
          type={showPassword ? 'text' : 'password'}
        />
        <div className='flex items-center justify-center rounded-md rounded-l-none border border-l-0 border-gray-300 pr-1 dark:border-gray-600 dark:bg-gray-700'>
          <button
            onClick={() => setShowPassword(!showPassword)}
            className='dark:hover-text-white cursor-default  rounded-md p-1.5 text-gray-400 transition duration-300 hover:bg-gray-100 hover:text-gray-600 dark:hover:bg-gray-600 dark:hover:text-white'
          >
            <SvgIcon
              className='h-5 w-5'
              name={showPassword ? 'eye-off' : 'eye'}
            />
          </button>
        </div>
      </div>
    </div>
  )
}

const LoginButton = ({
  onClick,
  disabled,
}: {
  onClick: () => void
  disabled: boolean
}) => {
  // TODO: Add loading indicator
  return (
    <button
      onClick={onClick}
      className={cx(
        'my-2 mt-6 flex w-full cursor-default items-center justify-center rounded-lg  py-2 text-lg font-semibold  transition duration-200',
        !disabled &&
          'bg-brand-100 text-brand-500 dark:bg-brand-600 dark:text-white',
        disabled &&
          'bg-brand-100 text-brand-300 dark:bg-brand-700 dark:text-white/50'
      )}
    >
      登录
    </button>
  )
}

const OtherLoginMethods = ({
  method,
  setMethod,
}: {
  method: Method
  setMethod: (method: Method) => void
}) => {
  const otherLoginMethods: {
    id: Method
    name: string
  }[] = [
    {
      id: Method.QrCode,
      name: '二维码',
    },
    {
      id: Method.Email,
      name: '邮箱',
    },
    {
      id: Method.Phone,
      name: '手机',
    },
  ]
  return (
    <>
      <div className='mt-8 mb-4 flex w-full items-center'>
        <span className='h-px flex-grow bg-gray-300 dark:bg-gray-700'></span>
        <span className='mx-2 text-sm text-gray-400 '>or</span>
        <span className='h-px flex-grow bg-gray-300 dark:bg-gray-700'></span>
      </div>
      <div className='flex gap-3'>
        {otherLoginMethods.map(
          ({ id, name }) =>
            method !== id && (
              <button
                key={id}
                onClick={() => setMethod(id)}
                className='flex w-full cursor-default items-center justify-center rounded-lg bg-gray-100 py-2 text-gray-600 transition duration-300 hover:bg-gray-200 hover:text-gray-800 dark:bg-gray-600 dark:text-gray-200 dark:hover:bg-gray-500 dark:hover:text-gray-100'
              >
                <SvgIcon className='mr-2 h-5 w-5' name={id} />
                <span>{name}</span>
              </button>
            )
        )}
      </div>
    </>
  )
}

const saveCookie = (cookies: string) => {
  setCookies(cookies)
}

// Login with Email
const LoginWithEmail = () => {
  const [password, setPassword] = useState('')
  const [email, setEmail] = useState('')
  const navigate = useNavigate()

  const doLogin = useMutation(
    () =>
      loginWithEmail({
        email: email.trim(),
        md5_password: md5(password.trim()),
      }),
    {
      onSuccess: result => {
        if (result?.code !== 200) {
          toast(`Login failed: ${result.code}`)
          return
        }
        saveCookie(result.cookie)
        navigate(-1)
      },
      onError: error => {
        toast(`Login failed: ${error}`)
      },
    }
  )

  const handleLogin = () => {
    if (!email) {
      toast.error('Please enter email')
      return
    }
    if (!password) {
      toast.error('Please enter password')
      return
    }
    if (
      email.match(
        /^[^\s@]+@(126|163|yeah|188|vip\.163|vip\.126)\.(com|net)$/
      ) == null
    ) {
      toast.error('Please use netease email')
      return
    }

    doLogin.mutate()
  }

  return (
    <>
      <EmailInput {...{ email, setEmail }} />
      <PasswordInput {...{ password, setPassword }} />
      <LoginButton onClick={handleLogin} disabled={doLogin.isLoading} />
    </>
  )
}

// Login with Phone
const LoginWithPhone = () => {
  const [password, setPassword] = useState('')
  const [phone, setPhone] = useState('')
  const countryCode = useSnapshot(state).uiStates.loginPhoneCountryCode
  const setCountryCode = (countryCode: string) => {
    state.uiStates.loginPhoneCountryCode = countryCode
  }
  const navigate = useNavigate()

  const doLogin = useMutation(
    () => {
      return loginWithPhone({
        countrycode: Number(countryCode.replace('+', '').trim()) || 86,
        phone: phone.trim(),
        md5_password: md5(password.trim()),
      })
    },
    {
      onSuccess: result => {
        if (result?.code !== 200) {
          toast(`Login failed: ${result.code}`)
          return
        }
        saveCookie(result.cookie)
        navigate(-1)
      },
      onError: error => {
        toast(`Login failed: ${error}`)
      },
    }
  )

  const handleLogin = () => {
    if (!countryCode || !Number(countryCode.replace('+', '').trim())) {
      toast.error('Please enter country code')
      return
    }
    if (!phone) {
      toast.error('Please enter phone number')
      return
    }
    if (!password) {
      toast.error('Please enter password')
      return
    }

    doLogin.mutate()
  }

  return (
    <>
      <PhoneInput {...{ countryCode, setCountryCode, phone, setPhone }} />
      <PasswordInput {...{ password, setPassword }} />
      <LoginButton onClick={handleLogin} disabled={doLogin.isLoading} />
    </>
  )
}

// Login with QRCode
const LoginWithQRCode = () => {
  const [qrCodeMessage, setQrCodeMessage] = useState('打开网易云音乐，扫码登录')
  const [qrCodeImage, setQrCodeImage] = useState('')

  const navigate = useNavigate()

  const {
    data: key = { code: 200, data: { code: 200, unikey: 'Not Ready' } },
    status: keyStatus,
    refetch: refetchKey,
  } = useQuery(
    'qrCodeKey',
    async () => {
      const result = await fetchLoginQrCodeKey()
      if (result.data.code !== 200) {
        throw Error(`Failed to fetch QR code key: ${result.data.code}`)
      }
      return result
    },
    {
      retry: true,
      retryDelay: 500,
    }
  )

  useInterval(async () => {
    if (keyStatus !== 'success') return
    const qrCodeStatus = await checkLoginQrCodeStatus({ key: key.data.unikey })
    switch (qrCodeStatus.code) {
      case 800:
        refetchKey()
        break
      case 801:
        setQrCodeMessage('打开网易云音乐，扫码登录')
        break
      case 802:
        setQrCodeMessage('等待确认')
        break
      case 803:
        if (qrCodeStatus.cookie === undefined) {
          toast('checkLoginQrCodeStatus returned 803 without cookie')
          break
        }
        saveCookie(qrCodeStatus.cookie)
        navigate(-1)
        break
    }
  }, 1000)

  const qrCodeUrl = useMemo(
    () => `https://music.163.com/login?codekey=${key.data.unikey}`,
    [key]
  )

  useEffect(() => {
    const updateImage = async () => {
      const svg = await QRCode.toString(qrCodeUrl, {
        margin: 0,
        color: {
          light: '#ffffff00',
        },
        type: 'svg',
      })
      const path = domParser
        .parseFromString(svg, 'text/xml')
        .getElementsByTagName('path')[0]

      setQrCodeImage(path?.getAttribute('d') ?? '')
    }
    updateImage()
  }, [qrCodeUrl])

  return (
    <div className='flex flex-col items-center justify-center'>
      <div className='rounded-3xl border p-6 text-brand-500 dark:border-gray-700'>
        <svg
          xmlns='http://www.w3.org/2000/svg'
          width='270'
          height='270'
          viewBox='0 0 37 37'
          shapeRendering='crispEdges'
        >
          <path stroke='currentColor' d={qrCodeImage} />
        </svg>
      </div>
      <div className='mt-4 text-sm text-gray-500 dark:text-gray-200'>
        {qrCodeMessage}
      </div>
    </div>
  )
}

export default function Login() {
  const [method, setMethod] = useState<Method>(Method.Phone)

  return (
    <div className='grid h-full place-content-center'>
      <div className='w-80'>
        {method === Method.Email && <LoginWithEmail />}
        {method === Method.Phone && <LoginWithPhone />}
        {method === Method.QrCode && <LoginWithQRCode />}
        <OtherLoginMethods {...{ method, setMethod }} />
      </div>
    </div>
  )
}

// src/renderer/views/Login.vue
<script setup lang="ts">
import { setCookies } from '@renderer/utils/cookie'
import md5 from 'md5'
import {
  loginWithEmail,
  loginWithPhone,
  fetchLoginQrCodeKey,
  checkLoginQrCodeStatus,
} from '@renderer/api/auth'
import type { CheckLoginQrCodeStatusResponse } from '@renderer/api/auth'
import { useQRCode } from '@vueuse/integrations/useQRCode'

const store = useStore()
const router = useRouter()

// switch login method
type Method = 'qrcode' | 'email' | 'phone'
const method = ref<Method>('phone')
const otherLoginMethods: {
  id: Method
  name: string
}[] = [
  {
    id: 'qrcode',
    name: 'QR Code',
  },
  {
    id: 'email',
    name: 'Email',
  },
  {
    id: 'phone',
    name: 'Phone',
  },
]

const changeMethod = (newMethod: Method) => {
  method.value = newMethod
  if (newMethod === 'qrcode') {
    resumeQrCodeTimer()
  } else {
    pauseQrCodeTimer()
  }
}
const togglePassword = () => {
  showPassword.value = !showPassword.value
}

// handle post login
const handlePostLogin = (cookies: string | undefined) => {
  if (!cookies) {
    alert('登录失败 [no cookie returned]')
    return
  }
  setCookies(cookies)
  router.push('/library')
}

// handle qrcode login
const qrCodeKey = ref<string>('')
const qrCodeStatus = ref<CheckLoginQrCodeStatusResponse | undefined>(undefined)
const refreshQrCode = async () => {
  fetchLoginQrCodeKey().then(result => {
    if (!result.data.unikey) return
    qrCodeKey.value = result.data.unikey
  })
}
if (method.value === 'qrcode') refreshQrCode()
const qrCodeUrl = computed<string>(() => {
  return `https://music.163.com/login?codekey=${qrCodeKey.value}`
})
const qrCode = useQRCode(qrCodeUrl, {
  width: 1024,
  margin: 0,
  color: {
    dark: '#335eea', // TODO: change brand color
    light: '#ffffff00',
  },
})
const { pause: pauseQrCodeTimer, resume: resumeQrCodeTimer } = useIntervalFn(
  () => {
    checkLoginQrCodeStatus({ key: qrCodeKey.value }).then(result => {
      qrCodeStatus.value = result
      const code = result.code
      if (code === 800) refreshQrCode()
      if (code === 803) {
        pauseQrCodeTimer()
        handlePostLogin(result.cookie)
      }
    })
  },
  2000
)
const qrCodeMessage = computed<string>(() => {
  const table = {
    800: '二维码已失效，请重新扫码',
    802: '扫描成功，请在手机上确认登录',
    803: '登录成功，请稍等...',
  }
  const code = qrCodeStatus.value?.code
  if (code) if (table[code]) return table[code]
  return 'Open NetEase app, scan QR Code to login'
})

// handle phone & email login
const showPassword = ref<boolean>(false)
const email = ref<string>('')
const phone = ref<string>('')
const countryCode = toRef(store.uiStates, 'loginPhoneCountryCode')
const password = ref<string>('')
const login = () => {
  if (method.value === 'phone') doPhoneLogin()
  else doEmailLogin()
}
const doPhoneLogin = async () => {
  let countrycode = 86
  const newCountryCode = countryCode.value.replace('+', '').trim()
  if (Number(newCountryCode) !== NaN) {
    countrycode = Number(newCountryCode)
  }
  const result = await loginWithPhone({
    countrycode,
    phone: phone.value.trim(),
    password: password.value.trim(),
    md5_password: md5(password.value.trim()),
  })
  handlePostLogin(result.cookie)
}
const doEmailLogin = async () => {
  const result = await loginWithEmail({
    email: email.value.trim(),
    md5_password: md5(password.value.trim()),
  })
  handlePostLogin(result.cookie)
}
</script>

<template>
  <div class="grid h-full place-content-center">
    <div class="w-80">
      <div class="flex flex-col">
        <!-- Header -->
        <!-- <div
          class="flex flex-col items-center self-center mb-10 text-2xl font-bold text-gray-700"
        >
          <div class="flex items-center gap-3 mb-6">
            <img
              src="/images/yesplaymusic.png"
              alt="YesPlayMusic"
              class="w-12 h-12"
            />
            <SvgIcon name="x" class="w-6 h-6 text-gray-400" />
            <img
              src="/images/netease-music.png"
              alt="NetEase Music"
              class="w-12 h-12"
            />
          </div>
          Connect to Netease
        </div> -->

        <!-- Qr Code -->
        <div
          v-show="method === 'qrcode'"
          class="flex flex-col items-center justify-center"
        >
          <div class="rounded-3xl border p-6">
            <img :src="qrCode" alt="QR Code" class="no-drag" />
          </div>
          <div class="mt-4 text-sm text-gray-500">
            {{ qrCodeMessage }}
          </div>
        </div>

        <!-- Email input -->
        <div v-show="method === 'email'" class="w-full">
          <div class="mb-1 text-sm font-medium text-gray-700">Email</div>
          <input
            class="w-full rounded-md border border-gray-300 px-2 py-2"
            type="email"
            v-model="email"
          />
        </div>

        <!-- Phone input -->
        <div v-show="method === 'phone'" class="w-full">
          <div class="mb-1 text-sm font-medium text-gray-700">Phone</div>
          <div class="flex w-full">
            <input
              class="rounded-md rounded-r-none border border-r-0 border-gray-300 px-3 py-2"
              :class="{
                'w-14': countryCode.length <= 3,
                'w-16': countryCode.length == 4,
                'w-20': countryCode.length >= 5,
              }"
              type="text"
              v-model="countryCode"
              placeholder="+86"
            />
            <input
              class="flex-grow rounded-md rounded-l-none border border-gray-300 px-3 py-2"
              type="text"
              v-model="phone"
            />
          </div>
        </div>

        <!-- Password input -->
        <div v-show="method !== 'qrcode'" class="mt-3 flex w-full flex-col">
          <div class="mb-1 text-sm font-medium text-gray-700">Password</div>
          <div class="flex w-full">
            <input
              class="w-full rounded-md rounded-r-none border border-r-0 border-gray-300 px-2 py-2"
              :type="showPassword ? 'text' : 'password'"
              v-model="password"
            />
            <div
              class="flex items-center justify-center rounded-md rounded-l-none border border-l-0 border-gray-300 pr-1"
            >
              <button
                @click="togglePassword"
                class="cursor-default rounded p-1.5 text-gray-400 transition duration-300 hover:bg-gray-100 hover:text-gray-600"
              >
                <SvgIcon
                  class="h-5 w-5"
                  :name="showPassword ? 'eye-off' : 'eye'"
                />
              </button>
            </div>
          </div>
        </div>

        <!-- Login button -->
        <button
          v-show="method !== 'qrcode'"
          @click="login"
          class="my-2 mt-6 flex w-full cursor-default items-center justify-center rounded-lg bg-brand-100 py-2 text-lg font-semibold text-brand-500 transition duration-200"
        >
          Login
        </button>
      </div>

      <!-- Other login methods -->
      <div class="mt-8 mb-4 flex w-full items-center">
        <span class="h-px flex-grow bg-gray-300"></span>
        <span class="mx-2 text-sm text-gray-400">or</span>
        <span class="h-px flex-grow bg-gray-300"></span>
      </div>
      <div class="flex gap-3">
        <button
          v-for="item in otherLoginMethods"
          v-show="method !== item.id"
          @click="changeMethod(item.id)"
          class="flex w-full cursor-default items-center justify-center rounded-lg bg-gray-100 py-2 font-medium text-gray-600 transition duration-300 hover:bg-gray-200 hover:text-gray-800"
        >
          <SvgIcon class="mr-2 h-5 w-5" :name="item.id" />
          <span>{{ item.name }}</span>
        </button>
      </div>
    </div>
  </div>
</template>
