// src/renderer/views/Library.vue
<script setup lang="ts">
import useUserAccount from '@renderer/hooks/useUserAccount'
import useUserPlaylists from '@renderer/hooks/useUserPlaylists'
import useTracks from '@renderer/hooks/useTracks'
import usePlaylist from '@renderer/hooks/usePlaylist'
import { resizeImage } from '@renderer/utils/common'

const store = useStore()
const { data: userAccount, isLoading: isLoadingAccount } = useUserAccount()
const { data: userPlaylists, isLoading: isLoadingPlaylists } = useUserPlaylists(
  reactive({
    uid: computed(() => userAccount.value?.account?.id ?? 0),
    offset: 0,
  })
)

const { data: likedSongPlaylist } = usePlaylist(
  reactive({ id: computed(() => userPlaylists.value?.playlist[0].id ?? 0) }),
  true
)

const { data: userLikedSongs, isLoading: isLoadingLikedTracks } = useTracks(
  reactive({
    ids: computed(() => {
      return (
        likedSongPlaylist.value?.playlist?.tracks?.map(track => track.id) || []
      )
    }),
  })
)

const tabs: { name: string; id: string }[] = [
  {
    name: 'Playlists',
    id: 'playlists',
  },
  {
    name: 'Albums',
    id: 'albums',
  },
  {
    name: 'Artists',
    id: 'artists',
  },
  {
    name: 'Videos',
    id: 'videos',
  },
]
</script>

<template>
  <div>
    <!-- xxx's Library -->
    <div class="my-6 flex items-center text-3xl font-bold">
      <img
        v-if="!isLoadingAccount"
        class="mr-3 h-9 w-9 rounded-full"
        :src="
          userAccount?.profile?.avatarUrl
            ? resizeImage(userAccount.profile.avatarUrl, 'md')
            : ''
        "
      />
      <Skeleton v-else class="mr-3 h-9 w-9 rounded-full" />

      <span class="pb-1">{{ userAccount?.profile?.nickname }}'s Library </span>
    </div>

    <!-- Liked songs -->
    <div class="flex items-stretch">
      <!-- Liked songs card -->
      <div
        class="mr-4 flex h-[13.75rem] min-w-[24rem] flex-col justify-between rounded-2xl bg-brand-100 px-5 py-4 text-brand-500"
      >
        <ol class="text-sm">
          <li>Got the heat and the thrill</li>
          <li>Give you more than any pill</li>
          <li>Never running out of juice</li>
        </ol>
        <div class="flex items-end justify-between">
          <div>
            <div class="text-xl font-bold">Liked Songs</div>
            <div class="mt-1">
              {{ likedSongPlaylist?.playlist.trackCount || 0 }} liked songs
            </div>
          </div>
          <button
            class="flex h-11 w-11 transform cursor-default items-center justify-center rounded-full bg-brand-500 text-brand-100 shadow-lg transition duration-200 hover:scale-105 active:scale-95"
          >
            <SvgIcon class="ml-1 h-4 w-4 text-brand-100" name="play" />
          </button>
        </div>
      </div>
      <!-- Liked songs list -->
      <TrackList
        :tracks="userLikedSongs?.songs.slice(0, 8) || []"
        :col="2"
        :isLoading="isLoadingLikedTracks"
      />
    </div>

    <!-- Tabs -->
    <div class="mt-8 mb-4 flex gap-3.5">
      <div
        v-for="tab in tabs"
        class="btn-hover-animation rounded-lg px-3.5 py-1.5 text-lg font-semibold text-gray-600 after:bg-gray-100"
        :class="{
          'bg-gray-100': tab.id === 'playlists',
        }"
        >{{ tab.name }}</div
      >
    </div>

    <div>
      <!-- Playlist tab content -->
      <div>
        <CoverRow
          :playlists="userPlaylists?.playlist.slice(1) || []"
          subtitle="creator"
          :isSkeleton="isLoadingPlaylists"
        />
      </div>
    </div>
  </div>
</template>

// src/renderer/pages/Library.tsx
import CoverRow, { Subtitle } from '@/components/CoverRow'
import SvgIcon from '@/components/SvgIcon'
import useUserAlbums from '@/hooks/useUserAlbums'
import useLyric from '@/hooks/useLyric'
import usePlaylist from '@/hooks/usePlaylist'
import useUser from '@/hooks/useUser'
import useUserPlaylists from '@/hooks/useUserPlaylists'
import { player } from '@/store'
import { resizeImage } from '@/utils/common'
import { sample, chunk } from 'lodash-es'
import useUserArtists from '@/hooks/useUserArtists'

const LikedTracksCard = ({ className }: { className?: string }) => {
  const navigate = useNavigate()
  const { data: user } = useUser()

  const { data: playlists } = useUserPlaylists({
    uid: user?.account?.id ?? 0,
    offset: 0,
  })

  const { data: likedSongsPlaylist } = usePlaylist({
    id: playlists?.playlist?.[0].id ?? 0,
  })

  // Lyric
  const [trackID, setTrackID] = useState(0)

  useEffect(() => {
    if (trackID === 0) {
      setTrackID(
        sample(likedSongsPlaylist?.playlist.trackIds?.map(t => t.id) ?? []) ?? 0
      )
    }
  }, [likedSongsPlaylist?.playlist.trackIds, trackID])

  const { data: lyric } = useLyric({
    id: trackID,
  })

  const lyricLines = useMemo(() => {
    return (
      sample(
        chunk(
          lyric?.lrc.lyric
            ?.split('\n')
            ?.map(l => l.split(']')[1]?.trim())
            ?.filter(
              l =>
                l &&
                !l.includes('作词') &&
                !l.includes('作曲') &&
                !l.includes('纯音乐，请欣赏')
            ),
          3
        )
      ) ?? []
    )
  }, [lyric])

  const handlePlay = useCallback(
    (e: React.MouseEvent<HTMLButtonElement>) => {
      e.stopPropagation()
      if (!likedSongsPlaylist?.playlist.id) {
        toast('无法播放歌单')
        return
      }
      player.playPlaylist(likedSongsPlaylist.playlist.id)
    },
    [likedSongsPlaylist?.playlist.id]
  )

  return (
    <div
      onClick={() =>
        likedSongsPlaylist?.playlist.id &&
        navigate(`/playlist/${likedSongsPlaylist.playlist.id}`)
      }
      className={classNames(
        'relative flex h-full w-full flex-col justify-between rounded-2xl bg-brand-50 py-5 px-6 text-brand-600 ',
        className
      )}
    >
      <div className='text-sm'>
        {lyricLines.map((line, index) => (
          <div key={`${index}-${line}`}>{line}</div>
        ))}
      </div>
      <div>
        <div className='text-2xl font-bold'>我喜欢的音乐</div>
        <div className='mt-0.5 text-[15px]'>
          {likedSongsPlaylist?.playlist.trackCount ?? 0} 首歌
        </div>
      </div>

      <button
        onClick={handlePlay}
        className='btn-pressed-animation absolute bottom-6 right-6 grid h-11 w-11 cursor-default place-content-center rounded-full bg-brand-600 text-brand-50 shadow-lg'
      >
        <SvgIcon name='play-fill' className='ml-0.5 h-6 w-6' />
      </button>
    </div>
  )
}

const OtherCard = ({
  name,
  icon,
  className,
}: {
  name: string
  icon: string
  className?: string
}) => {
  return (
    <div
      className={classNames(
        'flex h-full w-full flex-col justify-between rounded-2xl bg-gray-100 text-lg font-bold',
        className
      )}
    >
      <SvgIcon name={icon} className='ml-3 mt-3 h-12 w-12' />
      <span className='m-4'>{name}</span>
    </div>
  )
}

const Playlists = () => {
  const { data: user } = useUser()

  const { data: playlists } = useUserPlaylists({
    uid: user?.account?.id ?? 0,
    offset: 0,
  })
  return (
    <div>
      <CoverRow
        playlists={playlists?.playlist?.slice(1) ?? []}
        subtitle={Subtitle.CREATOR}
      />
    </div>
  )
}

const Albums = () => {
  const { data: albums } = useUserAlbums({
    limit: 1000,
  })

  return (
    <div>
      <CoverRow albums={albums?.data ?? []} subtitle={Subtitle.ARTIST} />
    </div>
  )
}

const Artists = () => {
  const { data: artists } = useUserArtists()

  return (
    <div>
      <CoverRow artists={artists?.data ?? []} subtitle={Subtitle.ARTIST} />
    </div>
  )
}

const MVs = () => {
  return <div>施工中</div>
}

const Podcasts = () => {
  return <div>施工中</div>
}
interface TabsType {
  playlist: string
  album: string
  artist: string
  mv: string
  podcast: string
}

const TabHeader = ({
  activeTab,
  tabs,
  setActiveTab,
}: {
  activeTab: keyof TabsType
  tabs: TabsType
  setActiveTab: (tab: keyof TabsType) => void
}) => {
  return (
    <div className='mt-10 flex text-lg'>
      {Object.entries(tabs).map(([id, name]) => (
        <div
          key={id}
          onClick={() => setActiveTab(id as keyof TabsType)}
          className={classNames(
            'btn-pressed-animation mr-3  rounded-lg px-3.5 py-1.5 font-medium',
            activeTab === id
              ? 'bg-black/[.04]'
              : 'btn-hover-animation after:bg-black/[.04] dark:after:bg-white/10'
          )}
        >
          {name}
        </div>
      ))}
    </div>
  )
}

const Tabs = () => {
  const tabs = {
    playlist: '全部歌单',
    album: '专辑',
    artist: '艺人',
    mv: 'MV',
    podcast: '播客',
  }

  const [activeTab, setActiveTab] = useState<keyof TabsType>('playlist')

  return (
    <>
      <TabHeader
        activeTab={activeTab}
        tabs={tabs}
        setActiveTab={setActiveTab}
      />
      <div className='mt-6'>
        {activeTab === 'playlist' && <Playlists />}
        {activeTab === 'album' && <Albums />}
        {activeTab === 'artist' && <Artists />}
        {activeTab === 'mv' && <MVs />}
        {activeTab === 'podcast' && <Podcasts />}
      </div>
    </>
  )
}

const Library = () => {
  const { data: user } = useUser()

  const avatarUrl = useMemo(
    () => resizeImage(user?.profile?.avatarUrl ?? '', 'sm'),
    [user?.profile?.avatarUrl]
  )

  return (
    <div className='mt-8'>
      <div className='flex items-center text-[2.625rem] font-semibold'>
        <img src={avatarUrl} className='mr-3 mt-1 h-12 w-12 rounded-full' />
        {user?.profile?.nickname}的音乐库
      </div>

      <div className='mt-8 grid grid-cols-[2fr_1fr_1fr] grid-rows-2 gap-4'>
        <LikedTracksCard className='row-span-2' />
        <OtherCard name='云盘' icon='fm' className='' />
        <OtherCard name='本地音乐' icon='music-note' className='' />
        <OtherCard name='最近播放' icon='playlist' className='' />
        <OtherCard name='听歌排行' icon='music-library' className='' />
      </div>

      <Tabs />
    </div>
  )
}

export default Library
