// packages/renderer/src/components/ArtistsInline.tsx
const ArtistInline = ({
  artists,
  className,
}: {
  artists: Artist[]
  className?: string
}) => {
  if (!artists) return <div></div>

  return (
    <div className={classNames('line-clamp-1', className)}>
      {artists.map((artist, index) => (
        <span key={artist.name}>
          <span className={classNames({ 'hover:underline': !!artist.id })}>
            {artist.name}
          </span>
          {index < artists.length - 1 ? ', ' : ''}&nbsp;
        </span>
      ))}
    </div>
  )
}

export default ArtistInline

// src/components/ArtistsInLine.vue
<template>
  <span class="artist-in-line">
    <span v-for="(ar, index) in slicedArtists" :key="ar.id">
      <router-link :to="`/artist/${ar.id}`">{{ ar.name }}</router-link>
      <span v-if="index !== slicedArtists.length - 1">, </span>
    </span>
  </span>
</template>

<script>
export default {
  name: "ArtistInLine",
  props: {
    artists: {
      type: Array,
      required: true,
    },
    showFirstArtist: {
      type: Boolean,
      default: true,
    },
  },
  computed: {
    slicedArtists() {
      return this.showFirstArtist
        ? this.artists
        : this.artists.slice(1, this.artists.length);
    },
  },
};
</script>

<style lang="scss" scoped></style>
