// packages/web/components/Cover.tsx
import Icon from '@/web/components/Icon'
import { cx } from '@emotion/css'
import { useState } from 'react'

const Cover = ({
  imageUrl,
  onClick,
  roundedClass = 'rounded-xl',
  showPlayButton = false,
  showHover = true,
  alwaysShowShadow = false,
}: {
  imageUrl: string
  onClick?: () => void
  roundedClass?: string
  showPlayButton?: boolean
  showHover?: boolean
  alwaysShowShadow?: boolean
}) => {
  const [isError, setIsError] = useState(imageUrl.includes('3132508627578625'))

  return (
    <div onClick={onClick} className='group relative z-0'>
      {/* Neon shadow */}
      {showHover && (
        <div
          className={cx(
            'absolute top-2 z-[-1] h-full w-full scale-x-[.92] scale-y-[.96] bg-cover  blur-lg filter transition duration-300 ',
            roundedClass,
            !alwaysShowShadow && 'opacity-0 group-hover:opacity-60'
          )}
          style={{
            backgroundImage: `url("${imageUrl}")`,
          }}
        ></div>
      )}

      {/* Cover */}
      {isError ? (
        <div className='box-content flex aspect-square h-full w-full items-center justify-center rounded-xl border border-black border-opacity-5  bg-gray-800 text-gray-300 '>
          <Icon name='music-note' className='h-1/2 w-1/2' />
        </div>
      ) : (
        <img
          className={cx(
            'box-content aspect-square h-full w-full border border-black border-opacity-5 dark:border-white  dark:border-opacity-[.03]',
            roundedClass
          )}
          src={imageUrl}
          onError={() => imageUrl && setIsError(true)}
        />
      )}

      {/* Play button */}
      {showPlayButton && (
        <div className='absolute top-0 hidden h-full w-full place-content-center group-hover:grid'>
          <button className='btn-pressed-animation grid h-11 w-11 cursor-default place-content-center rounded-full border border-white border-opacity-[.08] bg-white bg-opacity-[.14] text-white backdrop-blur backdrop-filter transition-all hover:bg-opacity-[.44]'>
            <Icon className='ml-0.5 h-6 w-6' name='play-fill' />
          </button>
        </div>
      )}
    </div>
  )
}

export default Cover

// src/components/Cover.vue
<template>
  <div style="position: relative">
    <div
      class="cover"
      @mouseover="focus = true"
      @mouseleave="focus = false"
      :style="coverStyle"
      :class="{
        'hover-float': hoverEffect,
        'hover-play-button': showPlayButton,
      }"
      @click="clickToPlay ? play() : goTo()"
    >
      <button
        class="play-button"
        v-if="showPlayButton"
        :style="playButtonStyle"
        @click.stop="playButtonClicked"
      >
        <svg-icon icon-class="play" />
      </button>
    </div>

    <transition name="fade" v-if="hoverEffect">
      <img class="shadow" v-show="focus" :src="url" :style="shadowStyle"
    /></transition>
    <img
      class="shadow"
      v-if="alwaysShowShadow"
      :src="url"
      :style="shadowStyle"
    />
  </div>
</template>

<script>
import { playAlbumByID, playPlaylistByID, playArtistByID } from "@/utils/play";

export default {
  name: "Cover",
  props: {
    id: Number,
    type: String,
    url: String,
    hoverEffect: Boolean,
    showPlayButton: Boolean,
    alwaysShowShadow: Boolean,
    showBlackShadow: Boolean,
    clickToPlay: Boolean,
    size: {
      type: Number,
      default: 208,
    },
    shadowMargin: {
      type: Number,
      default: 12,
    },
    radius: {
      type: Number,
      default: 12,
    },
    playButtonSize: {
      type: Number,
      default: 48,
    },
  },
  data() {
    return {
      focus: false,
      shadowStyle: {},
      playButtonStyle: {},
    };
  },
  created() {
    this.shadowStyle = {
      height: `${this.size}px`,
      width: `${~~(this.size * 0.96)}px`,
      top: `${this.shadowMargin}px`,
      right: `${~~(this.size * 0.02)}px`,
      borderRadius: `${this.radius}px`,
    };
    this.playButtonStyle = {
      height: `${this.playButtonSize}px`,
      width: `${this.playButtonSize}px`,
    };
  },
  computed: {
    coverStyle() {
      return {
        backgroundImage: `url('${this.url}')`,
        boxShadow: this.showBlackShadow
          ? "0 12px 16px -8px rgba(0, 0, 0, 0.2)"
          : "",
        height: `${this.size}px`,
        width: `${this.size}px`,
        borderRadius: `${this.radius}px`,
        cursor: this.clickToPlay ? "default" : "pointer",
      };
    },
  },
  methods: {
    play() {
      if (this.type === "album") {
        playAlbumByID(this.id);
      } else if (this.type === "playlist") {
        playPlaylistByID(this.id);
      }
    },
    playButtonClicked() {
      if (this.type === "album") {
        playAlbumByID(this.id);
      } else if (this.type === "playlist") {
        playPlaylistByID(this.id);
      } else if (this.type === "artist") {
        playArtistByID(this.id);
      }
    },
    goTo() {
      this.$router.push({ name: this.type, params: { id: this.id } });
    },
  },
};
</script>

<style lang="scss" scoped>
.cover {
  position: relative;
  padding: 0;
  background-size: cover;
  display: flex;
  justify-content: center;
  align-items: center;
  transition: transform 0.3s;
}

.hover-float {
  &:hover {
    transform: scale(1.02);
    box-shadow: 0 12px 16px -8px rgba(0, 0, 0, 0.05);
  }
}

.hover-play-button {
  &:hover {
    .play-button {
      opacity: 1;
      transform: unset;
    }
  }
  .play-button {
    &:hover {
      transform: scale(1.06);
    }
    &:active {
      transform: scale(0.94);
    }
  }
}

.shadow {
  position: absolute;
  filter: blur(16px) opacity(0.6);
  z-index: -1;
  height: 208px;
  transform: scale(0.98);
}
[data-theme="dark"] {
  .shadow {
    filter: blur(16px) brightness(68%);
    transform: scale(0.96);
  }
}

.play-button {
  opacity: 0;
  display: flex;
  justify-content: center;
  align-items: center;
  // right: 72px;
  // top: 72px;
  border: none;
  backdrop-filter: blur(12px) brightness(96%);
  background: transparent;
  color: white;
  border-radius: 50%;
  cursor: default;
  transition: 0.2s;
  .svg-icon {
    height: 50%;
    margin: {
      left: 3px;
    }
  }
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s;
}
.fade-enter, .fade-leave-to /* .fade-leave-active below version 2.1.8 */ {
  opacity: 0;
}
</style>
