// src/components/ArtistsInLine.vue
<template>
  <span class="artist-in-line">
    <span v-for="(ar, index) in slicedArtists" :key="ar.id">
      <router-link :to="`/artist/${ar.id}`">{{ ar.name }}</router-link>
      <span v-if="index !== slicedArtists.length - 1">, </span>
    </span>
  </span>
</template>

<script>
export default {
  name: "ArtistInLine",
  props: {
    artists: {
      type: Array,
      required: true,
    },
    showFirstArtist: {
      type: Boolean,
      default: true,
    },
  },
  computed: {
    slicedArtists() {
      return this.showFirstArtist
        ? this.artists
        : this.artists.slice(1, this.artists.length);
    },
  },
};
</script>

<style lang="scss" scoped></style>

// packages/web/components/New/ArtistsInLine.tsx
import { useNavigate } from 'react-router-dom'
import { cx } from '@emotion/css'

const ArtistInline = ({
  artists,
  className,
  disableLink,
  onClick,
  hoverClassName,
}: {
  artists: Artist[]
  className?: string
  hoverClassName?: string
  disableLink?: boolean
  onClick?: (artistId: number) => void
}) => {
  const navigate = useNavigate()
  const handleClick = (id: number) => {
    if (id === 0 || disableLink) return
    if (!onClick) {
      navigate(`/artist/${id}`)
    } else {
      onClick(id)
    }
  }

  if (!artists) return <div></div>

  return (
    <div
      className={cx(
        !className?.includes('line-clamp') && 'line-clamp-1',
        className
      )}
    >
      {artists.map((artist, index) => (
        <span key={`${artist.id}-${artist.name}`}>
          <span
            onClick={() => handleClick(artist.id)}
            className={cx(!!artist.id && !disableLink && hoverClassName)}
          >
            {artist.name}
          </span>
          {index < artists.length - 1 ? ', ' : ''}&nbsp;
        </span>
      ))}
    </div>
  )
}

export default ArtistInline
